name = "UnitBlockAngular"
uuid = "14f8afec-b63c-4272-9b79-c31d0438941a"
authors = ["mtanneau <mathieu.tanneau@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Tulip = "6dd1b50a-3aae-11e9-10b5-ef983d2400fa"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
